version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
    - discovery.type=single-node
    ports:
    - "127.0.0.1:9200:9200"
  kibana:
    image: kibana:7.6.2
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
  logstash:
    image: logstash:7.6.2
    links:
    - elasticsearch
    volumes:
    - ./config-dir:/config-dir
    command: logstash --path.settings=/config-dir
    depends_on:
    - elasticsearch
    ports:
    - "5044:5044"
    - "5045:5045"
  visualizations:
    build: visualizations

