version: "3"
services:
  elasticsearch:
    image: elasticsearch:6.7.1
    ports: 
    - "9200:9200"
    - "9300:9300"
  kibana:
    image: kibana:6.7.1
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
  logstash:
    image: logstash:6.7.1
    links:
    - elasticsearch
    volumes:
    - ./config-dir:/config-dir
    command: logstash --path.settings=/config-dir
    depends_on:
    - elasticsearch
    ports:
    - "5044:5044"
