version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.4.3
    restart: unless-stopped
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    ports:
    - "127.0.0.1:9200:9200"
    volumes:
    - ./data/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.4.3
    restart: unless-stopped
    ports:
    - "5601:5601"
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - xpack.security.enabled=false
  logstash:
    image: logstash:8.4.3
    restart: unless-stopped
    links:
    - elasticsearch
    volumes:
    - ./config-dir:/config-dir:ro
    command: logstash --path.settings=/config-dir
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
    - "5044:5044"
    - "5045:5045"
  init:
    image: alpine/curl
    entrypoint: /bin/sh
    command:
    - -c
    - |
      echo "hello world"
      while ! curl -sq http://elasticsearch:9200; do
        echo "Waiting for elasticsearch to start...";
        sleep 3;
      done
      while ! curl -sq --fail http://kibana:5601/api/status; do
        echo "Waiting for kibana to start..."
        sleep 3;
      done

      curl -X PUT http://elasticsearch:9200/enologmessage -H 'Content-Type: application/json' -d '
      {
        "mappings": {
          "dynamic": false,
          "properties": {
            "@timestamp": {
              "type": "date_nanos"
            },
            "@version": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "agent": {
              "properties": {
                "ephemeral_id": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "hostname": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "id": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "type": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "version": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                }
              }
            },
            "ecs": {
              "properties": {
                "version": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                }
              }
            },
            "enologs": {
              "properties": {
                "currentRoundId": {
                  "type": "long"
                },
                "flag": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "function": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "message": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "method": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "module": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "relatedRoundId": {
                  "type": "long"
                },
                "serviceName": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "severity": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "severityLevel": {
                  "type": "long"
                },
                "taskChainId": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "taskId": {
                  "type": "long"
                },
                "teamId": {
                  "type": "long"
                },
                "teamName": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "timestamp": {
                  "type": "date_nanos"
                },
                "tool": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "type": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "type": "keyword",
                      "ignore_above": 256
                    }
                  }
                },
                "variantId": {
                  "type": "long"
                }
              }
            },
            "log": {
              "properties": {
                "file": {
                  "properties": {
                    "path": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    }
                  }
                },
                "offset": {
                  "type": "long"
                }
              }
            },
            "tags": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        }
      }
      '

      curl -X POST http://kibana:5601/api/data_views/data_view -H 'Content-Type: application/json' -H 'kbn-xsrf: reporting' -d '
      {
        "data_view": {
          "title": "enologmessage",
          "name": "enologmessage",
          "timeFieldName": "enologs.timestamp"
        }
      }'

      curl -X POST http://kibana:5601/api/data_views/data_view -H 'Content-Type: application/json' -H 'kbn-xsrf: reporting' -d '
      {
        "data_view": {
          "title": "enostatisticsmessage",
          "name": "enostatisticsmessage",
          "timeFieldName": "enostatistics.timestamp"
        }
      }'
