version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.1.2
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    ports:
    - "127.0.0.1:9200:9200"
    #volumes:
    #- ./es_data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.1.2
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - xpack.security.enabled=false
  logstash:
    image: logstash:8.1.2
    links:
    - elasticsearch
    volumes:
    - ./config-dir:/config-dir
    command: logstash --path.settings=/config-dir
    depends_on:
    - elasticsearch
    ports:
    - "5044:5044"
    - "5045:5045"
